AppBundle\Entities\ValueObjects\PostAuthor:
    type: embeddable

    fields:
        name:
            type: string
            length: 100

    embedded:
        email:
            class: AppBundle\Entities\ValueObjects\EmailAddress
